name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: windows-fetch-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja/CMake
        uses: lukka/get-cmake@latest
        
      - name: Configure and Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build

      - name: Upload Windows App
        uses: actions/upload-artifact@v4
        with:
          name: RamusGreenhouse-Windows
          path: |
            build/**/RamusGreenhouse.exe
            build/**/assets/